# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'may_hoc_giaodien.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 458)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_img_detec = QtWidgets.QPushButton(self.centralwidget)
        self.btn_img_detec.setGeometry(QtCore.QRect(150, 370, 131, 61))
        self.btn_img_detec.setObjectName("btn_img_detec")
        #self.btn_vid_detec = QtWidgets.QPushButton(self.centralwidget)
        #self.btn_vid_detec.setGeometry(QtCore.QRect(490, 370, 131, 61))
        #self.btn_vid_detec.setObjectName("btn_vid_detec")
        self.btn_real = QtWidgets.QPushButton(self.centralwidget)
        self.btn_real.setGeometry(QtCore.QRect(420, 150, 211, 61))
        self.btn_real.setObjectName("btn_KET QUA")
        self.img = QtWidgets.QLabel(self.centralwidget)
        self.img.setGeometry(QtCore.QRect(30, 230, 371, 131))
        self.img.setText("")
        self.img.setPixmap(QtGui.QPixmap("../.designer/backup/results.jpg"))
        self.img.setScaledContents(True)
        self.img.setWordWrap(False)
        self.img.setOpenExternalLinks(False)
        self.img.setObjectName("img")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 150, 191, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 170, 191, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 190, 191, 21))
        self.label_7.setObjectName("label_7")
        self.btn_img = QtWidgets.QPushButton(self.centralwidget)
        self.btn_img.setGeometry(QtCore.QRect(10, 370, 131, 61))
        self.btn_img.setObjectName("btn_img")
        #self.btn_vid = QtWidgets.QPushButton(self.centralwidget)
        #self.btn_vid.setGeometry(QtCore.QRect(350, 370, 131, 61))
        #self.btn_vid.setObjectName("btn_vid")
        self.txt_img = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_img.setEnabled(True)
        self.txt_img.setGeometry(QtCore.QRect(420, 230, 211, 131))
        self.txt_img.setObjectName("txt_img")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ĐỒ ÁN 1"))
        self.btn_img_detec.setText(_translate("MainWindow", "IMGAGE_DETECTION"))
        #self.btn_vid_detec.setText(_translate("MainWindow", "VIDEO_DETECTION"))
        self.btn_real.setText(_translate("MainWindow", "KET QUA HIEN THI"))
        self.label_2.setText(_translate("MainWindow", "ĐỒ ÁN 1"))
        self.label_3.setText(_translate("MainWindow", "TÊN ĐỀ TÀI: NHẬN DIỆN BIỂN SỐ XE"))
        self.label_5.setText(_translate("MainWindow", "THÀNH VIÊN:"))
        self.label_6.setText(_translate("MainWindow", "20521142 - Tran Quang Chuyen"))
        self.label_7.setText(_translate("MainWindow", "20522151 - Le Xuan Viet"))
        self.btn_img.setText(_translate("MainWindow", "IMGAGE"))
        #self.btn_vid.setText(_translate("MainWindow", "VIDEO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
